//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2011, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 1K program for KCPSM6 in a 7-Series device using a 
// RAMB18E1 primitive.
//
// Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
//       expansion with minimum changes being required to the hardware description. 
//       Only the lower 10-bits of the address are actually used for the 1K address range
//       000 to 3FF hex.  
//
// Program defined by 'C:\work\HDSDI\X7_GTX_SDI\KC705Pblaze\XCSi5324.psm'.
//
// Generated by KCPSM6 Assembler: 04 Oct 2012 - 13:57:06. 
//
//
//
module XCSi5324 (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire [17:0] data_in_a;
wire [17:0] data_out_a;
wire [13:0] address_b;
wire [17:0] data_in_b;
wire [17:0] data_out_b;
wire        enable_b;
wire        clk_b;
wire [3:0]  we_b;
//
//
assign address_a = {address[9:0], 4'b0000};
assign instruction = data_out_a[17:0];
assign data_in_a = {16'h0000, address[11:10]};
//
assign address_b = 14'b00000000000000;
assign data_in_b = data_out_b[17:0];
assign enable_b = 1'b0;
assign we_b = 4'h0;
assign clk_b = 1'b0;
//
// 
RAMB18E1 # ( .READ_WIDTH_A              (18),
             .WRITE_WIDTH_A             (18),
             .DOA_REG                   (0),
             .INIT_A                    (16'b000000000000000000),
             .RSTREG_PRIORITY_A         ("REGCE"),
             .SRVAL_A                   (36'h000000000000000000),
             .WRITE_MODE_A              ("WRITE_FIRST"),
             .READ_WIDTH_B              (18),
             .WRITE_WIDTH_B             (18),
             .DOB_REG                   (0),
             .INIT_B                    (36'h000000000000000000),
             .RSTREG_PRIORITY_B         ("REGCE"),
             .SRVAL_B                   (36'h000000000000000000),
             .WRITE_MODE_B              ("WRITE_FIRST"),
             .INIT_FILE                 ("NONE"),
             .SIM_COLLISION_CHECK       ("ALL"),
             .RAM_MODE                  ("TDP"),
             .RDADDR_COLLISION_HWCONFIG ("DELAYED_WRITE"),
             .SIM_DEVICE                ("7SERIES"),
             .INIT_00                   (256'hF00010FF013214D0029914E89602F00210FFD1041103D1041183D08310008000),
             .INIT_01                   (256'h40603080B003360701BC158214D0416630039082F004F003D0081000F0011097),
             .INIT_02                   (256'h9011605FC0F0BF01901020A8D00130036034C0F0AFE0301390081E00F003D008),
             .INIT_03                   (256'h204AD002300320166052DF10603DDF036F00E0E0AFE030132016605FC0F0BF04),
             .INIT_04                   (256'h158816402044363F01BC150320166052DF10004E017C15035640363F01BC1503),
             .INIT_05                   (256'h90102016017C1503562001BC1503205C36DF01BC15036059D010A0E05000017C),
             .INIT_06                   (256'h060040F04F064F064F064F06300F9040E0A3400E90410000FF049F11D040F001),
             .INIT_07                   (256'h1523017C15209640017C1522017C151F9640017C15199640017C1502017C1502),
             .INIT_08                   (256'h9640017C152A9640017C15299640017C15289640017C1524017C15219640017C),
             .INIT_09                   (256'h15379640017C1530017C152D9640017C152F017C152C9640017C152E017C152B),
             .INIT_0A                   (256'h9B226016DA809A2199206016DA809A212016F003D0085080B0032016004E017C),
             .INIT_0B                   (256'hD93520D2D90420D2D903201620CFDA0420C4DA0220BBDA013A073B076016DB80),
             .INIT_0C                   (256'hD962201620FFD93020FFD92F20DED9EB20DBD96E20D5D90A201620D8D93620D8),
             .INIT_0D                   (256'h1C051005212D10031C04212D10021C03212D10011C01212D10001C002016210C),
             .INIT_0E                   (256'h1C091007212DDB031C081008212DDB021C071006212DDB011C061004212DDB00),
             .INIT_0F                   (256'h100C2016212DDB071C0C100A212DDB061C0B100B212DDB051C0A1009212DDB04),
             .INIT_10                   (256'h212DDB001C1010102016212DDB071C0F100D212DDB061C0E100E212DDB051C0D),
             .INIT_11                   (256'h212DDB041C141012212DDB031C131013212DDB021C121011212DDB011C11100F),
             .INIT_12                   (256'h2016CFC0BF022016212DDB071C171015212DDB061C161016212DDB051C151014),
             .INIT_13                   (256'h16291513017C163F1506017C16121504017C16451503017C16821502205FFC02),
             .INIT_14                   (256'h017C16051521017C16401519017C163E1518017C16FE1515017C163F1514017C),
             .INIT_15                   (256'h1589017C165A1530017C165A152D017C1607152A017C16071529017C16051524),
             .INIT_16                   (256'h40081000D68101BC14D095801000D0026173D0015000017C16401588017C1601),
             .INIT_17                   (256'h03401100D10411025000D083400840081000017C968114D095805000D0834008),
             .INIT_18                   (256'h0360A195025E0350D1041100A195025ED10401100110011001100110011033FE),
             .INIT_19                   (256'h01100110011001100110D10411005000D00110000199500020000199A195025E),
             .INIT_1A                   (256'h011001100110011001100110011001101103D104110201100110011001100110),
             .INIT_1B                   (256'h03401100D104110250000110011001100110011001100110011001100110D104),
             .INIT_1C                   (256'h011001100110A195025E0350A195025ED10401100110011001100110011033FE),
             .INIT_1D                   (256'h01101102D104110321D9D0019004011001100110011001100110011001100110),
             .INIT_1E                   (256'hD104530103400110011001100110011001100110011001100110011001100110),
             .INIT_1F                   (256'h1208A195025ED104011001100110011001100110011001100110011001101100),
             .INIT_20                   (256'hD104011001100110011001100110011001100110011001100110011001101103),
             .INIT_21                   (256'h0110D1041101620092014600400ED10490040110011001100110011001101101),
             .INIT_22                   (256'hD104110301100110011001100110011001100110011001100110011001100110),
             .INIT_23                   (256'h011001100110011001101102D1041100D1040110011001100110011001101101),
             .INIT_24                   (256'h0110011001101103D10401100110011001100110011001100110011001100110),
             .INIT_25                   (256'h31FE1208500020000110011001100110011001100110D1040110011001100110),
             .INIT_26                   (256'h011001100110011001100110011001100110011001105102D1045101E2634306),
             .INIT_27                   (256'hD1045101625F9201D104011001100110011001100110011031FDD10401100110),
             .INIT_28                   (256'h01100110D1045102011001100110011001100110011001100110011001100110),
             .INIT_29                   (256'h0110011033FE03401100D10411025000400ED104900431FD0110011001100110),
             .INIT_2A                   (256'h0000500020000199A195025E0360D1041100A195025ED1040110011001100110),
             .INIT_2B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_30                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_31                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_32                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_33                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_34                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_35                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_36                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_37                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_38                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_39                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_00                  (256'h208820880550D08A2822230A088B2808D2CC20B43434D00A00830A8888822222),
             .INITP_01                  (256'h2D0D0D0D0D0D0D0D0820820A6DDDDDB7776DDD0C3030A82A0882208820820882),
             .INITP_02                  (256'h08A520294A0CCA0820820820820820820820820AD2D0D0D0D0D0D0D0D0B43434),
             .INITP_03                  (256'h3A0000008000000008C00000038E8000088000020000200000224A2E388E8000),
             .INITP_04                  (256'h8D8000200000008D080002000080000000088000800000002356000080000000),
             .INITP_05                  (256'h000000000000000000000000000000000000000022E23A000022600008000000),
             .INITP_06                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_07                  (256'h0000000000000000000000000000000000000000000000000000000000000000))
 kcpsm6_rom( .ADDRARDADDR               (address_a),
             .ENARDEN                   (enable),
             .CLKARDCLK                 (clk),
             .DOADO                     (data_out_a[15:0]),
             .DOPADOP                   (data_out_a[17:16]), 
             .DIADI                     (data_in_a[15:0]),
             .DIPADIP                   (data_in_a[17:16]), 
             .WEA                       (2'b00),
             .REGCEAREGCE               (1'b0),
             .RSTRAMARSTRAM             (1'b0),
             .RSTREGARSTREG             (1'b0),
             .ADDRBWRADDR               (address_b),
             .ENBWREN                   (enable_b),
             .CLKBWRCLK                 (clk_b),
             .DOBDO                     (data_out_b[15:0]),
             .DOPBDOP                   (data_out_b[17:16]), 
             .DIBDI                     (data_in_b[15:0]),
             .DIPBDIP                   (data_in_b[17:16]), 
             .WEBWE                     (we_b),
             .REGCEB                    (1'b0),
             .RSTRAMB                   (1'b0),
             .RSTREGB                   (1'b0));
//
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE XCSi5324.v
//
////////////////////////////////////////////////////////////////////////////////////
